# Generated by Django 3.0 on 2019-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled')], default=None, max_length=200),
            preserve_default=False,
        ),
    ]
