# Generated by Django 3.0 on 2019-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_worktime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Finished')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled')]),
        ),
    ]
